# Generated by Django 5.0.3 on 2024-06-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategori',
            new_name='Category',
        ),
    ]
