# Generated by Django 5.0.3 on 2024-07-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Ecommerce', '0014_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
