# Generated by Django 5.0.3 on 2024-07-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Ecommerce', '0022_payment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warna', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='warna',
        ),
        migrations.AddField(
            model_name='product',
            name='warna',
            field=models.ManyToManyField(to='app_Ecommerce.warna'),
        ),
    ]
