# Generated by Django 5.0.3 on 2024-07-07 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Ecommerce', '0023_warna_remove_product_warna_product_warna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warna',
        ),
        migrations.AddField(
            model_name='product',
            name='warna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_Ecommerce.warna'),
        ),
    ]
